# [\#825 Issue](https://github.com/ethereum/solidity/issues/825) `closed`: bool results can equal to true even when function calls throw

#### <img src="https://avatars.githubusercontent.com/u/294690?u=e23412bf01405892cda463c8feda0d3080fd4253&v=4" width="50">[balboah](https://github.com/balboah) opened issue at [2016-08-05 16:19](https://github.com/ethereum/solidity/issues/825):

in this example:

```
contract priced {
    address public tokenContractAddress;

    modifier costs(uint256 amount) {
        Token tc = Token(tokenContractAddress);
        bool result = tc.transfer();
        if (result == true) _
    }
}

contract Token {
    function transfer() returns (bool success) {
        throw;
    }
}

contract Foo is priced {
    uint public called;

    function Foo(address tokenContract) {
        tokenContract = 0;
    }

    function bar() costs(1) {
        called++;
    }
}
```

When tokenContractAddress is 0, we will always have a true result in the priced modifier, as opposed to what I would expect.

This happened to me where I incorrectly set the tokenContract instead of tokenContractAddress.


#### <img src="https://avatars.githubusercontent.com/u/142290?u=cc1c365b40d8b3b84e2622effc8c8f7792e2a216&v=4" width="50">[holiman](https://github.com/holiman) commented at [2016-08-05 16:19](https://github.com/ethereum/solidity/issues/825#issuecomment-237917347):

Well, you're invoking `transfer()`on a contract (`0`) which does not have any code. Thus, the contract `0` does not throw. Nothing strange about this. EDIT: I agree it's strange that it returns `true`

#### <img src="https://avatars.githubusercontent.com/u/9620836?u=6a792ee80e79b87f64f6aa16bd323e5a7a7bad97&v=4" width="50">[Denton-L](https://github.com/Denton-L) commented at [2016-08-05 16:19](https://github.com/ethereum/solidity/issues/825#issuecomment-237937200):

I don't know what's going on but I have additional information to provide:

Take the following set of contracts:

```
contract A {
    B b = B(address(0));

    function caller() returns (uint) {
        return b.dummy();
    }

    function methodSignature() constant returns (bytes4) {
        return bytes4(sha3("dummy()"));
    }
}

contract B {
    function dummy() returns (uint) {
        throw;
    }
}
```

Calling `caller()` seems to consistently return `0x32e43a1100000000000000000000000000000000000000000000000000000000`. The first four bytes of this are equal to the return value of `methodSignature()` (the method signature of `dummy()`). For some reason, it is returning the method signature.

Here is what I suspect is happening, though I could be wrong though because I don't know the internals of the EVM too well.

When `caller()` calls `dummy()`, it has to push the method signature onto the stack. Since `B`'s code is all zeros (since it hasn't been initialised), when it tries to execute, it'll hit `0x00` which corresponds to the `STOP` opcode. When it "returns", the method signature will still be on the stack, because it hasn't been cleared by  call to `dummy()`, so `caller()` will read that as the return value.

Of course, in your case, any non-zero value, such as the method signature, will be `true`.

#### <img src="https://avatars.githubusercontent.com/u/142290?u=cc1c365b40d8b3b84e2622effc8c8f7792e2a216&v=4" width="50">[holiman](https://github.com/holiman) commented at [2016-08-05 16:19](https://github.com/ethereum/solidity/issues/825#issuecomment-237942872):

Some details are wrong, but I think you're on the right track. 

So when doing a `call`, the evm gets two sets of "pointers". The first being [memory in offset, memory in size], which in points to a memory location containing the `calldata` (method signature). And then there's [memory out offset, memory out size]. And that's where the EVM will write the return values. And if there is no return value, the EVM will not touch the [memout - memout+memoutsz] area, leaving it _as is_ . 

So, I guess that Solidity compiler defaults to reusing the `mem_in` - area for output. Which is economically sound (less memory area used == less gas consumed) but becomes very fragile, since the return values depend on the method signature. Fun quirk, actually quite deadly.

#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2016-08-05 16:19](https://github.com/ethereum/solidity/issues/825#issuecomment-237944240):

I think I've raised the same issue a while ago: https://github.com/ethereum/solidity/issues/520

#### <img src="https://avatars.githubusercontent.com/u/924397?u=4c3e5a7b67595961461f5ac3e1dd41aca26a5b4b&v=4" width="50">[nmushegian](https://github.com/nmushegian) commented at [2016-08-05 16:19](https://github.com/ethereum/solidity/issues/825#issuecomment-237988628):

When you call empty code it doesn't throw, so you get garbage. See: https://github.com/nexusdev/dappsys/blob/develop/contracts/lang/fallback_tests.sol

#### <img src="https://avatars.githubusercontent.com/u/294690?u=e23412bf01405892cda463c8feda0d3080fd4253&v=4" width="50">[balboah](https://github.com/balboah) commented at [2016-08-05 16:19](https://github.com/ethereum/solidity/issues/825#issuecomment-238013126):

Yes I realized that I didn't initialize it properly and thus didn't get a `throw`. But I really don't think an uninitialized contract should be able to return something that can be interpreted as true, or being able to change the default value of a variable. It must be a big source of hard to track bugs and a security concern to many.

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2016-08-05 16:19](https://github.com/ethereum/solidity/issues/825#issuecomment-238838034):

Fixed as far as it is fixable in https://github.com/ethereum/solidity/pull/839

#### <img src="https://avatars.githubusercontent.com/u/294690?u=e23412bf01405892cda463c8feda0d3080fd4253&v=4" width="50">[balboah](https://github.com/balboah) commented at [2016-08-05 16:19](https://github.com/ethereum/solidity/issues/825#issuecomment-238842599):

that was quick! üëç


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2022.05.23 at 03:51:38.]
