# [\#2505 Issue](https://github.com/ethereum/solidity/issues/2505) `closed`: Handle parsing errors properly in JSON I/O
**Labels**: `bug :bug:`


#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) opened issue at [2017-07-03 10:40](https://github.com/ethereum/solidity/issues/2505):

```
pragma solidity ^0.4.11; contract Contract { this is a syntax error }"}
```

reports an error properly on the CLI:
```
Warning: This is a pre-release compiler version, please do not use it in production.
113.sol:1:51: Error: Expected identifier, got 'Is'
pragma solidity ^0.4.11; contract Contract { this is a syntax error }
                                                  ^


```

but is not properly handled in standard-json:

```
{"errors":[{"component":"general","formattedMessage":"Internal exception in StandardCompiler::compileInternal: /Users/alex/Projects/solidity/libsolidity/interface/CompilerStack.cpp(508): Throw in function const dev::solidity::SourceUnit &dev::solidity::CompilerStack::ast(const string &) const\nDynamic exception type: boost::exception_detail::clone_impl<dev::solidity::CompilerError>\nstd::exception::what: std::exception\n[dev::tag_comment*] = Parsing was not successful.\n","message":"Internal exception in StandardCompiler::compileInternal: /Users/alex/Projects/solidity/libsolidity/interface/CompilerStack.cpp(508): Throw in function const dev::solidity::SourceUnit &dev::solidity::CompilerStack::ast(const string &) const\nDynamic exception type: boost::exception_detail::clone_impl<dev::solidity::CompilerError>\nstd::exception::what: std::exception\n[dev::tag_comment*] = Parsing was not successful.\n","severity":"error","type":"InternalCompilerError"}]}
```

(Found in https://github.com/ethereum/solc-js/issues/113)




-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2022.05.23 at 03:51:38.]
