# [\#4810 Issue](https://github.com/ethereum/solidity/issues/4810) `closed`: Contract to contract function call with 0.4.23

#### <img src="https://avatars.githubusercontent.com/u/868061?v=4" width="50">[juztin](https://github.com/juztin) opened issue at [2018-08-13 19:47](https://github.com/ethereum/solidity/issues/4810):

## Description

With `solc` 0.4.23, contract to contract function calls appear to fail when the the address reference, used to link the contracts, is set/updated after deployment.

_(Link to [ethereum.stackexchange](https://ethereum.stackexchange.com/questions/56369/cant-get-contract-to-contract-function-calls-working/56454#56454) describing the issue_)

## Environment

- Compiler version: 0.4.23 _(using Docker image `ethereum/solc:stable`)_
- Framework/IDE (e.g. Truffle or Remix): Vim
- EVM execution environment / backend / blockchain client: Geth 1.8.13-stable
- Operating system: Linux / OSX

## Steps to Reproduce

Say we have a `Parent` contract that looks like:

```solidity
contract Parent {
    int value;

    function setValue(int v) external {
        value = v;
    }

    function getValue() external view returns (int) {
        return value;
    }

    function getSender() external view returns (address) {
        return msg.sender;
    }
}
```

...and a `Child` contract like:

```solidity
contract Child {
    Parent parent;

    function setParent(address a) external {
        parent = Parent(a);
    }

    function getValue() external view returns (int) {
        return parent.getValue();
    }

    function getSender() external view returns (address) {
        return parent.getSender();
    }
}
```

If we compile the above contracts, and generate the ABI with:

```shell
% solc --bin Child.sol Parent.sol
% solc --abi Child.sol Parent.sol
```

Then deploy the resulting contracts into Geth, using either web3js, Mist, etc.
After calling `setParent` of the child, sending the address of `Parent`, we end up with:

 - `getValue()` always yields `0`
 - `getSender()` always yields `0x0`

Using version(s) `0.4.24`, `0.4.22`, 0.4.21`, or 0.4.20` to compile the byte-code/abi, and re-deploying, seems to resolve the issue.  
It appears to be an issue when casting the address to a contract.  

Adding the below method always returns `0`:

```solidity
    function getValue(address addr) external view returns (int) {
        Parent p = Parent(addr);
        p.getValue();
        return 1;
    }
```

We had partial success when chaning the `setParent` function to:  
_(this only fixed it in this example, our real code still failed to work)_

```solidity
    function setParent(Parent p) external {
        parent = p;
    }
```

And, we had 100% success when using:

```solidity
function getValue() external view returns (int value) {
    address addr = address(parent);
    bytes4 sig = bytes4(keccak256("getValue()"));

    assembly {
       let o := mload(0x40) // Empty storage pointer
       mstore(o,sig)        // Push function signature to memory (function signature is 4 bytes/0x04)
       //mstore(add(ptr,0x40), someInt32Argument); // Append function argument after signature
       // From here, the call data size (input) would be functiona signature size + sum(argument size)
       //   4bytes + 0 in this case, or 4bytes + 32bytes in the above commented `mstore`

       let success := call(
           15000,           // Gas limit
           addr,            // To address
           0,               // No ether to transfer
           o,               // Input location ptr
           0x04,            // Input size (0)
           o,               // Store oputput over input
           0x20)            // Output size (32 bytes)

       value := mload(o)
       mstore(0x40,add(o,0x04))
    }
}
```

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2018-08-13 19:47](https://github.com/ethereum/solidity/issues/4810#issuecomment-412657540):

Are you sure the result you get is `0` or might it be that the transaction fails? I'm asking because the function you are calling is a `view` function, which uses the `staticcall` opcode with recent compiler versions (when set to `byzantium' vm mode, which is the default). What is the VM mode of the geth node you are testing against?

#### <img src="https://avatars.githubusercontent.com/u/868061?v=4" width="50">[juztin](https://github.com/juztin) commented at [2018-08-13 19:47](https://github.com/ethereum/solidity/issues/4810#issuecomment-412659686):

@chriseth sorry, yes, the call does fail, it's just displaying the default value of the return type _(in Mist)_.

We've tried this on both a private node, which is using the default, as well as running geth in `--dev` mode. Same results in both instances.

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2018-08-13 19:47](https://github.com/ethereum/solidity/issues/4810#issuecomment-412775987):

@juztin then the solution might be to set geth to the correct evm version / hard fork for the testnet you are running, or use a public testnet.

#### <img src="https://avatars.githubusercontent.com/u/868061?v=4" width="50">[juztin](https://github.com/juztin) commented at [2018-08-13 19:47](https://github.com/ethereum/solidity/issues/4810#issuecomment-412914732):

Thanks @chriseth, although I can't seem to find anything around Geth and setting an EVM version.
To keep development going, we've simply changed `solc` to a version other than 0.4.23 _(it just gave us the fuzzies using `stable`)_.

As for Geth, we've run this in multiple different configurations while troubleshooting. We've tried numerous private node configurations, which were very simple, along with using just a `--dev` instance. We even tried an older version of Geth, just to try and rule things out _(we only tested a single, older version, but had the same outcome, so we didn't poke around too much here)_

When using the same running Geth/Mist instance, and using Mist to deploy the byte-code generated from `solc` 0.4.23, we get the issue. But, if we use the same `.sol` files used during byte-code generation in Mist's source code deploy _(Mist 0.10.0 uses solc `0.4.18`)_, everything is fine.  
_(we also deployed outside of Mist, we just kept testing this way in hopes of ruling out things we may have been doing)_

I guess it just feels weird to me that versions before/after 0.4.23 all work as expected. It's only when using the one particular version:

 - [X] - 0.4.18 _(Mist's internal compiler)_
 - [X] - 0.4.20
 - [X] - 0.4.21
 - [X] - 0.4.22
 - [ ] - 0.4.23
 - [X] - 0.4.24

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2018-08-13 19:47](https://github.com/ethereum/solidity/issues/4810#issuecomment-412936766):

Are you able to retrieve a VM trace of the failing transaction?

This might be of help, too: https://github.com/ethereum/go-ethereum/issues/16931

Does it also happen in remix (while not being connected to some other node)?

Could you provide full steps to reproduce this issue, at best in remix?

#### <img src="https://avatars.githubusercontent.com/u/868061?v=4" width="50">[juztin](https://github.com/juztin) commented at [2018-08-13 19:47](https://github.com/ethereum/solidity/issues/4810#issuecomment-413355435):

Hey @chriseth, sorry for taking this long to get back to ya.

Dang! I've spent far too long on this. This totally fixed all the issues we've been having. Sorry for posting this issue here, it just seemed like it made the most sense at the time. I wish Geth had this documented better, or just made it the a default value that your could turn off, instead of on...

Thanks a ton =)

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2018-08-13 19:47](https://github.com/ethereum/solidity/issues/4810#issuecomment-413370407):

We are always very worried about any misbehaviour of the compiler, especially in the code generation part, which this seems to be about. It is especially disturbing that it does not work in one specific version, and the fact that it has been fixed in the meantime is not a big relief, because there might be vulnerable contracts out there. Still, since the call is failing and not returning invalid data, it does not seem too big a deal, so unless we can clearly reproduce this, I would keep it closed. Thanks for your time!

#### <img src="https://avatars.githubusercontent.com/u/868061?v=4" width="50">[juztin](https://github.com/juztin) commented at [2018-08-13 19:47](https://github.com/ethereum/solidity/issues/4810#issuecomment-413407925):

Just to put your mind at ease, I re-ran my original tests on a different machine, with a different Geth instance, and the results proved to be inconsistent. I'm guessing without the Byzantium setting, Geth was just acting sporadic and it wasn't anything specific to the compiler. _(just making some assumptions)_

Thanks again for helping =)

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2018-08-13 19:47](https://github.com/ethereum/solidity/issues/4810#issuecomment-413533337):

Phew, thanks! :)


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2022.05.23 at 03:51:38.]
