# [\#1440 Issue](https://github.com/ethereum/solidity/issues/1440) `closed`: LLL: panic keyword is broken
**Labels**: `bug :bug:`


#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) opened issue at [2016-11-26 15:04](https://github.com/ethereum/solidity/issues/1440):

```
{ (panic) }
```

results in:

"Reference to tag without position."

@chriseth, the changes of #1122 broke it.


#### <img src="https://avatars.githubusercontent.com/u/102482?v=4" width="50">[zigguratt](https://github.com/zigguratt) commented at [2016-12-02 15:10](https://github.com/ethereum/solidity/issues/1440#issuecomment-264475810):

This test shows the failure quite nicely:
```
BOOST_AUTO_TEST_CASE(enclosed_panic)
{
        char const* sourceCode = "(seq (panic))";
        compileAndRunWithoutCheck(sourceCode);
        BOOST_REQUIRE(m_output.empty());
}
```
This produces
```
[dev::tag_comment*] = Reference to tag without position.
```


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
