# [\#2410 Issue](https://github.com/ethereum/solidity/issues/2410) `closed`: Error out when function has payable specified multiple times

#### <img src="https://avatars.githubusercontent.com/u/138426?u=3117125771b06e3aa8da468c8f41e4038d717974&v=4" width="50">[federicobond](https://github.com/federicobond) opened issue at [2017-06-15 22:34](https://github.com/ethereum/solidity/issues/2410):

Test case:

````
contract test {
    function foo() payable payable payable {}
}
````

#### <img src="https://avatars.githubusercontent.com/u/138426?u=3117125771b06e3aa8da468c8f41e4038d717974&v=4" width="50">[federicobond](https://github.com/federicobond) commented at [2017-06-15 22:42](https://github.com/ethereum/solidity/issues/2410#issuecomment-308885332):

Happens with `constant` too:
````
contract test {
    function foo() constant constant constant {}
}
````

#### <img src="https://avatars.githubusercontent.com/u/7756785?u=2893ea91743ac89ee3846d1f5c7209720e834129&v=4" width="50">[VoR0220](https://github.com/VoR0220) commented at [2017-06-16 00:27](https://github.com/ethereum/solidity/issues/2410#issuecomment-308900262):

Oooo...thats nasty.


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
