# [\#3006 PR](https://github.com/ethereum/solidity/pull/3006) `merged`: Always return a valid pointer in Exception::what()

#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) opened issue at [2017-10-02 10:42](https://github.com/ethereum/solidity/pull/3006):

Fixes #2567 and #2832.

#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2017-10-02 14:46](https://github.com/ethereum/solidity/pull/3006#issuecomment-333556748):

@chfast please create a new PR for your suggested changes

#### <img src="https://avatars.githubusercontent.com/u/573380?u=6cd4b0f473d862749cbed137d0bb32b726ae071f&v=4" width="50">[chfast](https://github.com/chfast) commented at [2017-10-02 14:50](https://github.com/ethereum/solidity/pull/3006#issuecomment-333558008):

https://github.com/ethereum/solidity/pull/3009


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
