# [\#4707 Issue](https://github.com/ethereum/solidity/issues/4707) `closed`: Crash when accessing empty name variable slot
**Labels**: `bug :bug:`


#### <img src="https://avatars.githubusercontent.com/u/388605?u=c038834687e1b11f1cfc815c338b03a3938a235b&v=4" width="50">[mattaereal](https://github.com/mattaereal) opened issue at [2018-08-06 21:04](https://github.com/ethereum/solidity/issues/4707):

_This issue is being reported as part of the current audit being held by Zeppelin Solutions to Solidity's compiler (tag v0.4.24)._

## Description 
The parser does not detect the usage of a `_slot` syntax on an empty variable name. 

## Error in file
Attempt to resolve empty name
`libsolidity/analysis/DeclarationContainer.cpp(128)`

## Displayed message
`Throw in function std::vector<const dev::solidity::Declaration*> dev::solidity::DeclarationContainer::resolveName(const ASTString&, bool, bool) const`

## Example code
```solidity
pragma solidity ^0.4.24;
contract CrashContract {
   function () internal {
       assembly {
           _slot
       }
   }
}
```


#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2018-08-06 23:07](https://github.com/ethereum/solidity/issues/4707#issuecomment-410880550):

Still reproducible:
```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/analysis/DeclarationContainer.cpp(127): Throw in function vector<const dev::solidity::Declaration *> dev::solidity::DeclarationContainer::resolveName(const dev::solidity::ASTString &, bool, bool) const
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: Attempt to resolve empty name.
[dev::tag_comment*] = Attempt to resolve empty name.
```


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
