# [\#3793 PR](https://github.com/ethereum/solidity/pull/3793) `merged`: Rational number limit

#### <img src="https://avatars.githubusercontent.com/u/20012009?u=61e903cf16bc5f3353db1d571401e2e71b6f61ed&v=4" width="50">[erak](https://github.com/erak) opened issue at [2018-03-28 14:11](https://github.com/ethereum/solidity/pull/3793):

Fixes #3327
Fixes #3759

#### <img src="https://avatars.githubusercontent.com/u/20012009?u=61e903cf16bc5f3353db1d571401e2e71b6f61ed&v=4" width="50">[erak](https://github.com/erak) commented at [2018-03-28 17:58](https://github.com/ethereum/solidity/pull/3793#issuecomment-376978827):

@axic I've started testing with two examples of those DoS cases and they're not hanging anymore. After the limit is reached, the function is still called, but ``m_value.denominator()`` is constant from there on and calling ``pow()`` results in the same large number.
Currently the error messages don't help to understand the issue I guess, but there might be some options for making them richer.

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2018-03-29 07:58](https://github.com/ethereum/solidity/pull/3793#issuecomment-377154874):

Please also add a test for bit-shifts.

#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2018-04-04 15:31](https://github.com/ethereum/solidity/pull/3793#issuecomment-378642918):

> After the limit is reached, the function is still called, but m_value.denominator() is constant from there on and calling pow() results in the same large number.

For those test cases it probably is the case, however for the case of doing a very large exp, it will just "hang" or take a lot of time.

Please add such a test case too.

#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2018-04-04 16:43](https://github.com/ethereum/solidity/pull/3793#issuecomment-378666906):

Maybe useful to look at the test cases of #3348 (an earlier attempt of the same problem).

Additionally, some random notes:
- `uint a = 1E1000000 ** 1E1000000;`
- `100000000000E1250 = 1E1261`

#### <img src="https://avatars.githubusercontent.com/u/1347491?v=4" width="50">[ekpyron](https://github.com/ekpyron) commented at [2018-04-13 17:41](https://github.com/ethereum/solidity/pull/3793#issuecomment-381210250):

OK - ``boost::multiprecision::msb`` is only introduced with boost 1.55 and trusty is still on boost 1.54 (somehow I thought it'd be at least 1.57) :-D.

I'll try to find a good workaround over the weekend.

The ``ci/circleci: test_x86`` result ``Too long with no output (exceeded 10m0s)`` is not a good sign as well, though...

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2018-04-16 09:08](https://github.com/ethereum/solidity/pull/3793#issuecomment-381531555):

@ekpyron were you able to find something? Otherwise I will pick this up later.

#### <img src="https://avatars.githubusercontent.com/u/1347491?v=4" width="50">[ekpyron](https://github.com/ekpyron) commented at [2018-04-16 09:13](https://github.com/ethereum/solidity/pull/3793#issuecomment-381533093):

@chriseth I was just about to look into it. Unfortunately I think we may have to use ``floor(log2(...))`` instead of ``msb`` again and therefore also deal with some ``bigfloat`` type... I'll check whether there's a better option.

#### <img src="https://avatars.githubusercontent.com/u/1347491?v=4" width="50">[ekpyron](https://github.com/ekpyron) commented at [2018-04-16 09:49](https://github.com/ethereum/solidity/pull/3793#issuecomment-381543741):

@chriseth This now contains a workaround for boost < 1.55, which is a naive (but therefore sufficiently simple) implementation of ``msb``. We have to keep an eye on the running times of the tests, though.

#### <img src="https://avatars.githubusercontent.com/u/1347491?v=4" width="50">[ekpyron](https://github.com/ekpyron) commented at [2018-04-16 10:23](https://github.com/ethereum/solidity/pull/3793#issuecomment-381552679):

Now the ``ci/circleci: test_x86`` test works again as well and doesn't seem to take longer than before the PR - not sure what the problem was before...


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
