# [\#6879 Issue](https://github.com/ethereum/solidity/issues/6879) `closed`: [yul] Exception due to syntax error in object access builtin function
**Labels**: `bug :bug:`, `fuzz blocker`


#### <img src="https://avatars.githubusercontent.com/u/2388185?v=4" width="50">[bshastry](https://github.com/bshastry) opened issue at [2019-06-03 07:21](https://github.com/ethereum/solidity/issues/6879):

## Description

Syntax errors such as these should not throw an exception

```
{codecopy(datasize(6),5,5)}
```

but they do

```
$ echo "{codecopy(datasize(6),5,5)}" | solc --strict-assembly -
Warning: Yul and its optimizer are still experimental. Please use the output with care.

======= <stdin> (EVM) =======

Pretty printed source:
object "object" {
    code { codecopy(datasize(6), 5, 5) }
}

Exception while assembling: /home/bhargava/work/github/solidity/libyul/backends/evm/EVMDialect.cpp(130): Throw in function {anonymous}::createBuiltins(langutil::EVMVersion, bool)::<lambda(const yul::FunctionCall&, yul::AbstractAssembly&, yul::BuiltinContext&, std::function<void()>)>
Dynamic exception type: boost::exception_detail::clone_impl<yul::YulException>
std::exception::what: Could not find assembly object <6>.
[dev::tag_comment*] = Could not find assembly object <6>.
```

## Environment

- Compiler version: latest develop

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2019-06-26 13:48](https://github.com/ethereum/solidity/issues/6879#issuecomment-505883174):

To solve this, I think we need to provide the list of objects to AsmAnalysis.


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
