# [\#10159 Issue](https://github.com/ethereum/solidity/issues/10159) `closed`: contract warns if fallback payable is defined without receive defined
**Labels**: `language design :rage4:`, `low effort`, `low impact`, `closed due inactivity`, `stale`


#### <img src="https://avatars.githubusercontent.com/u/224810?u=9d4bdd31329b33f97dbee8e1e3e6f01fa1369d09&v=4" width="50">[3esmit](https://github.com/3esmit) opened issue at [2020-10-29 21:58](https://github.com/ethereum/solidity/issues/10159):

## Description

I'm having to include this
```
    /**
     * @notice Fails on calls with no `msg.data` but with `msg.value`
     */
    receive() external payable {
        revert("bad call");
    }

```

into the smart contract so it stops warning me about not using receive. I use fallback payable, but I need msg.data, so `receive()`(calls with no msg.data, but msg.value) should always fail if I didn't defined a `receive()` function 

This warning is not fair: `Warning: This contract has a payable fallback function, but no receive ether function. Consider adding a receive ether function.`

If I add this receive function, that only reverts, than compiler will include it on the ABI of the contract. But this conflics with the warning and with https://solidity.readthedocs.io/en/v0.7.4/security-considerations.html#take-warnings-seriously

Instead, I added the first line of fallback as `require(msg.data.length > 0, "bad call")`. 

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2020-11-02 10:32](https://github.com/ethereum/solidity/issues/10159#issuecomment-720385568):

In my opinion, your explicit receive function that always reverts in a good solution - it makes it explicit what happens if you send this contract Ether. The fact that the function is present in the ABI may be unfortunate, but any other function present in the ABI could also always revert.

Would you propose to remove the warning altogether?

#### <img src="https://avatars.githubusercontent.com/u/224810?u=9d4bdd31329b33f97dbee8e1e3e6f01fa1369d09&v=4" width="50">[3esmit](https://github.com/3esmit) commented at [2020-11-02 16:26](https://github.com/ethereum/solidity/issues/10159#issuecomment-720577732):

The warning seems wrong because the intended design is not having a receive() function. 

If I haven't defined receive(), than any address.transfer() to the contract should fail automatically. 

Currently I am getting this warning, and I have to:
```solidity
    fallback() external payable {
        require(msg.data.length > 0, "bad call");
        //(...) my fallback logic that uses msg.data, and possibly use msg.value
    }
```

#### <img src="https://avatars.githubusercontent.com/u/224810?u=9d4bdd31329b33f97dbee8e1e3e6f01fa1369d09&v=4" width="50">[3esmit](https://github.com/3esmit) commented at [2020-11-02 19:03](https://github.com/ethereum/solidity/issues/10159#issuecomment-720665379):

Yes, I propose to remove the warning altogether, because the warning makes it seems I am doing a bad design on the contract, while I have to do this way for the compiler understand that this ABI entrypoint does not exists. 

If I am not using the "receive() external payable", or calls from .transfer(), or msg.data.lenght == 0 with msg.value > 0, than should be a proper way of doing it without rising warnings and without including in ABI an function that cannot be used.  

I cannot accept this solution as "ignore the warning" because this will make all warnings ignorable. 
I cannot accept this solution as "include the receive that always reverts" because it will make an incorrect ABI which can confuse other developers or users.

#### <img src="https://avatars.githubusercontent.com/u/137030?v=4" width="50">[cameel](https://github.com/cameel) commented at [2021-02-19 21:46](https://github.com/ethereum/solidity/issues/10159#issuecomment-782382518):

Since this is somewhat related to #2691, which is now closed, I'm adding this to the design backlog to be discussed on the next call. We should make a decision about what to do with this warning.

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2021-02-22 13:03](https://github.com/ethereum/solidity/issues/10159#issuecomment-783358166):

I still think the current situation is the best, but I'm open for discussion.

#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2021-02-24 14:18](https://github.com/ethereum/solidity/issues/10159#issuecomment-785107156):

The split between fallback and receive was discussed and introduced via #3198. It is a length discussions containing reasoning.

@hrkrshnn brought up that the warning is not particularly clear and could trigger people to just include an empty receive function, which is likely not what they want. We should consider improving the error message to avoid such situations.

#### <img src="https://avatars.githubusercontent.com/u/17516057?u=044fe75d85f3d61d63f6f8ca6dd6bb86fe639756&v=4" width="50">[VladLupashevskyi](https://github.com/VladLupashevskyi) commented at [2021-06-21 20:04](https://github.com/ethereum/solidity/issues/10159#issuecomment-865308298):

The fallback function is used in proxy contracts and this warning is a bit annoying when you have to deal with lots of these contracts.
I agree with @3esmit that such an approach to ignore this warning makes all warnings (possibly important ones) also ignorable.
It would be great if there would be an option to disable this warning for a particular line.

#### <img src="https://avatars.githubusercontent.com/in/15368?v=4" width="50">[github-actions](https://github.com/apps/github-actions) commented at [2023-03-11 12:04](https://github.com/ethereum/solidity/issues/10159#issuecomment-1464897265):

This issue has been marked as stale due to inactivity for the last 90 days.
It will be automatically closed in 7 days.

#### <img src="https://avatars.githubusercontent.com/in/15368?v=4" width="50">[github-actions](https://github.com/apps/github-actions) commented at [2023-03-19 12:04](https://github.com/ethereum/solidity/issues/10159#issuecomment-1475230170):

Hi everyone! This issue has been automatically closed due to inactivity.
If you think this issue is still relevant in the latest Solidity version and you have something to [contribute](https://docs.soliditylang.org/en/latest/contributing.html), feel free to reopen.
However, unless the issue is a concrete proposal that can be implemented, we recommend starting a language discussion on the [forum](https://forum.soliditylang.org) instead.


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
