# [\#8501 Issue](https://github.com/ethereum/solidity/issues/8501) `closed`: [solc] Throws ICE "Invalid conversion to calldata type"
**Labels**: `bug :bug:`


#### <img src="https://avatars.githubusercontent.com/u/2388185?v=4" width="50">[bshastry](https://github.com/bshastry) opened issue at [2020-03-17 10:52](https://github.com/ethereum/solidity/issues/8501):

## Description

```
contract C {
  uint[] m_data_dyn;
  function s(uint[6][] calldata b) external {
    m_data_dyn = b[1];
  }
}
```

throws

https://github.com/ethereum/solidity/blob/435c9dae718eeef645edb715293c4c687240ee5e/libsolidity/codegen/CompilerUtils.cpp#L975-L980

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc <input.sol>
Internal compiler error during compilation:
/home/bhargava/work/github/solidity/libsolidity/codegen/CompilerUtils.cpp(980): Throw in function void solidity::frontend::CompilerUtils::convertType(const solidity::frontend::Type &, const solidity::frontend::Type &, bool, bool, bool)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: Invalid conversion to calldata type.
[solidity::util::tag_comment*] = Invalid conversion to calldata type.
```

#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2020-05-07 20:42](https://github.com/ethereum/solidity/issues/8501#issuecomment-625486331):

Is not reproducible anymore. Not sure which PR fixed it.

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2020-05-07 22:26](https://github.com/ethereum/solidity/issues/8501#issuecomment-625528044):

Yep, first fixed version is 0.6.5.


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
