# [\#14305 PR](https://github.com/ethereum/solidity/pull/14305) `closed`: Do not assume successful analysis on fatal error.

#### <img src="https://avatars.githubusercontent.com/u/1347491?v=4" width="50">[ekpyron](https://github.com/ekpyron) opened issue at [2023-06-05 17:32](https://github.com/ethereum/solidity/pull/14305):

This came up when looking into refactoring analysis to split into legacy/experimental analysis.

Currently, we set the ``AnalysisPerformed`` state, in case there was a fatal error during analysis. However, we precisely raise fatal errors, in cases in which we *don't* guarantee a sane state.

This should not be a visible change in behaviour outside of "error recovery" mode (which is experimental and unsupported anyways) - hence I didn't add a changelog entry.

Without error recovery, it looks like both CLI and standard-json actually specifically *don't* rely on the ``AnalysisPerformed`` state (probably precisely since it wasn't set reliably due to this).

Is there *any* case of a fatal analysis error in which we *still* want to pretend that analysis was successful?

#### <img src="https://avatars.githubusercontent.com/u/137030?v=4" width="50">[cameel](https://github.com/cameel) commented at [2023-06-06 10:44](https://github.com/ethereum/solidity/pull/14305#issuecomment-1578429536):

> Is there any case of a fatal analysis error in which we still want to pretend that analysis was successful?

But does `AnalysisPerformed` actually indicate successful analysis? From the way it's all set up, it seems to me that it just marks it as performed and you must also use `hasError()` to check if it failed or not. Even unsuccessful analysis dirties stack's state by leaving stuff in `m_errorReporter`, `m_unhandledSMTLib2Queries` or `m_globalContext` so it makes sense to remember it was already performed and require a reset to be able to rerun it (and currently `analyze()` has a check against `m_stackState >= AnalysisPerformed` at the beginning, which this PR would bypass).

I mean, the way you see it makes sense too and it looks to me that we ended up with an inconsistent mix between these two views. For example, like you pointed out, we do `return` in the `try` block after some analysis steps without changing the state or setting `m_hasErrors` - we should be raising `FatalError` instead. The functions in `CompilerStack` returning various artifacts also don't consistently check `hasError()` - some do, but others just check the state.

#### <img src="https://avatars.githubusercontent.com/u/1347491?v=4" width="50">[ekpyron](https://github.com/ekpyron) commented at [2023-06-06 16:21](https://github.com/ethereum/solidity/pull/14305#issuecomment-1579079716):

> > Is there any case of a fatal analysis error in which we still want to pretend that analysis was successful?
> 
> But does `AnalysisPerformed` actually indicate successful analysis? From the way it's all set up, it seems to me that it just marks it as performed and you must also use `hasError()` to check if it failed or not. Even unsuccessful analysis dirties stack's state by leaving stuff in `m_errorReporter`, `m_unhandledSMTLib2Queries` or `m_globalContext` so it makes sense to remember it was already performed and require a reset to be able to rerun it (and currently `analyze()` has a check against `m_stackState >= AnalysisPerformed` at the beginning, which this PR would bypass).
> 
> I mean, the way you see it makes sense too and it looks to me that we ended up with an inconsistent mix between these two views. For example, like you pointed out, we do `return` in the `try` block after some analysis steps without changing the state or setting `m_hasErrors` - we should be raising `FatalError` instead. The functions in `CompilerStack` returning various artifacts also don't consistently check `hasError()` - some do, but others just check the state.

That's not how things currently work either, though. If you have any syntax error, then you can start analysis and still retain ``m_stackState < AnalysisPerformed``.

#### <img src="https://avatars.githubusercontent.com/u/1347491?v=4" width="50">[ekpyron](https://github.com/ekpyron) commented at [2023-06-06 17:12](https://github.com/ethereum/solidity/pull/14305#issuecomment-1579155586):

Or you can have a ``DeclarationTypeChecker`` error and retain ``m_stackState < AnalysisPerformed`` while having not only a "dirtied" error reporter, but also "dirtied" ``m_globalContext``.

#### <img src="https://avatars.githubusercontent.com/u/137030?v=4" width="50">[cameel](https://github.com/cameel) commented at [2023-06-07 09:19](https://github.com/ethereum/solidity/pull/14305#issuecomment-1580279305):

> That's not how things currently work either, though. If you have any syntax error, then you can start analysis and still retain ``m_stackState < AnalysisPerformed``.

Yes, I see that but the only thing that breaks this picture are those early returns, which to me seem like **the** bug here and the thing we should be fixing.

Currently fatal errors in analysis use the `fatal...Error()` methods of `ErrorReporter`, which throws `FatalError` and results in `AnalysisPerformed` and `m_hasError = true`. Non-fatal errors result in analysis steps returning `false`, which leads to state and `m_hasError` being unchanged. This seems backwards. And simply moving the state change earlier is not enough to fix that. We should have fatal and non-fatal errors both change the state and the flag the same way (unless `m_hasError` was meant to indicate specifically only fatal errors but I doubt that).

#### <img src="https://avatars.githubusercontent.com/u/1347491?v=4" width="50">[ekpyron](https://github.com/ekpyron) commented at [2023-06-07 10:04](https://github.com/ethereum/solidity/pull/14305#issuecomment-1580372446):

> > That's not how things currently work either, though. If you have any syntax error, then you can start analysis and still retain `m_stackState < AnalysisPerformed`.
> 
> Yes, I see that but the only thing that breaks this picture are those early returns, which to me seem like **the** bug here and the thing we should be fixing.
> 
> Currently fatal errors in analysis use the `fatal...Error()` methods of `ErrorReporter`, which throws `FatalError` and results in `AnalysisPerformed` and `m_hasError = true`. Non-fatal errors result in analysis steps returning `false`, which leads to state and `m_hasError` being unchanged. This seems backwards. And simply moving the state change earlier is not enough to fix that. We should have fatal and non-fatal errors both change the state and the flag the same way (unless `m_hasError` was meant to indicate specifically only fatal errors but I doubt that).

Just summarizing from the chat: That's true, but doing it that way would break the error recovery mode even more. Which is why we decided to finally remove that, since that'll get us back to a simpler and cleaner state.

#### <img src="https://avatars.githubusercontent.com/u/1347491?v=4" width="50">[ekpyron](https://github.com/ekpyron) commented at [2023-06-07 11:40](https://github.com/ethereum/solidity/pull/14305#issuecomment-1580619127):

I'm actually closing this in favour of @cameel removing the error recovery mode in a separate PR, which will supersede this one.


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
